"""Type stubs for pinocchio — C++ extension with no built-in .pyi files.

Declares only the symbols actually used by figaroh-plus. Extend as needed.
"""

from typing import Any
import numpy as np
import numpy.typing as npt

# === Classes ===

class Model: ...
class Data: ...
class Frame: ...
class Inertia: ...
class SE3: ...
class Force: ...
class Motion: ...

class RobotWrapper:
    model: Model
    data: Data
    collision_model: Any
    visual_model: Any
    def __init__(self, model: Model, collision_model: Any = ..., visual_model: Any = ...) -> None: ...
    def initFromURDF(self, filename: str, package_dirs: str = ..., root_joint: Any = ...) -> None: ...

# Joint models
class JointModelFreeFlyer: ...

# Geometry types
class GeometryObject: ...
class GeometryModel: ...

# Collision-related
class CollisionResult: ...
class DistanceResult: ...

# Quaternion
class Quaternion: ...

# Frame types
class FrameType:
    OP_FRAME: int
    LOCAL: int
    pass

# === Functions ===

def buildModelFromXML(xml: str, root_joint: Any = ...) -> Model: ...
def buildModelsFromUrdf(filename: str, package_dirs: str = ..., root_joint: Any = ...) -> tuple[Model, Any, Any]: ...
def buildGeomFromUrdf(model: Model, filename: str, package_dirs: str, geom_model: Any) -> Any: ...

def forwardKinematics(model: Model, data: Data, q: npt.NDArray) -> None: ...
def framesForwardKinematics(model: Model, data: Data, q: npt.NDArray) -> None: ...
def updateFramePlacements(model: Model, data: Data) -> None: ...
def updateGeometryPlacements(model: Model, data: Data, geom_model: Any) -> None: ...
def computeFrameJacobian(model: Model, data: Data, q: npt.NDArray, frame_id: int, rf_frame: int, J: npt.NDArray) -> None: ...
def computeFrameKinematicRegressor(model: Model, data: Data, frame_id: int, rf_frame: int, regressor: npt.NDArray) -> None: ...

def rnea(model: Model, data: Data, q: npt.NDArray, v: npt.NDArray, a: npt.NDArray) -> npt.NDArray: ...
def computeGeneralizedGravity(model: Model, data: Data, q: npt.NDArray) -> npt.NDArray: ...
def computeJointTorqueRegressor(model: Model, data: Data, q: npt.NDArray, v: npt.NDArray, a: npt.NDArray) -> npt.NDArray: ...

def centerOfMass(model: Model, data: Data, q: npt.NDArray, v: npt.NDArray = ..., a: npt.NDArray = ...) -> npt.NDArray: ...
def computeSubtreeMasses(model: Model, data: Data) -> None: ...

def computeCollisions(model: Model, data: Data, stop_at_first_collision: bool = ...) -> bool: ...
def computeCollision(model: Any, data: Any, pair_index: int) -> CollisionResult: ...
def computeDistance(model: Any, data: Any, pair_index: int) -> DistanceResult: ...
def removeCollisionPairs(model: Model, data: Data, geometry_model: Any, sr-model: str, sr-other: str = ...) -> None: ...

def computeDistance(model: Any, data: Any, pair_index: int) -> DistanceResult: ...

def difference(model: Model, q1: npt.NDArray, q2: npt.NDArray) -> npt.NDArray: ...
def randomConfiguration(model: Model, lower: npt.NDArray = ..., upper: npt.NDArray = ...) -> npt.NDArray: ...

def rpy(npt.NDArray) -> npt.NDArray: ...
def rpyToMatrix(r: float, p: float, y: float) -> npt.NDArray: ...
def SE3(...) -> SE3: ...

def PseudoInertia(mass: float, com: npt.NDArray, inertia: npt.NDArray) -> Inertia: ...
