from typing import Any

class MeshcatVisualizer:
    def __init__(self, model: Any, collision_model: Any, visual_model: Any) -> None: ...
    def display(self, q: Any) -> None: ...
    def play(self, qs: Any, dt: float) -> None: ...
    def loadViewerModel(self, rootNodeName: str = ...) -> None: ...
    def addSphere(self, name: str, radius: float, color: Any) -> None: ...
    def addCylinder(self, name: str, radius: float, length: float, color: Any) -> None: ...
    def addBox(self, name: str, x: float, y: float, z: float, color: Any) -> None: ...
    def applyConfiguration(self, name: str, placement: Any) -> None: ...
    def delete(self, name: str) -> None: ...
    def clean(self) -> None: ...
    viewer: Any

class GepettoVisualizer:
    def __init__(self, model: Any, collision_model: Any, visual_model: Any) -> None: ...
    def display(self, q: Any) -> None: ...
    def play(self, qs: Any, dt: float) -> None: ...
    def loadViewerModel(self, rootNodeName: str = ...) -> None: ...
    def addSphere(self, name: str, radius: float, color: Any) -> None: ...
    def addCylinder(self, name: str, radius: float, length: float, color: Any) -> None: ...
    def addBox(self, name: str, x: float, y: float, z: float, color: Any) -> None: ...
    def applyConfiguration(self, name: str, placement: Any) -> None: ...
    def delete(self, name: str) -> None: ...
    def clean(self) -> None: ...
